### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by dltmdrbtjd** [johj703/user_magazine#1]
- 로그인 구현에는 현재 문제가 없어보이네요. login한 상태에 대해서 지금 핸들링이 안되어보고 있는걸로 보여집니다. 여기서 이제 모든페이지에서 로그인한 상태를 어떻게 알고 유지할 수 있을까?에 대해서 고민하게 되는데요. 로그인한 상태를 체크하는 로직도 이미 작성해놓으신걸로 보입니다. 하지만 지금 이걸 어떤식으로 유지하고 사용하는지에 대해서 감이 안잡히신다면 현재 직접 작성하신 로그인 관련 로직에 대해서 다시 읽어보시고 Browser의 Cookie storage에 대해서 찾아보시고 이게 어떤건지 무슨 역할을 하는거고 어떻게 사용할 수 있는건지를 공부해보신다면 현재 발생한 문제를 해결하는데 도움이될거라고 생각합니다. 🤓

- 추가로 cookie뿐 아니라 session storage, local storage 등등 다양한 browser 내부 저장소가 있는데 각각의 차이점이 어떤거고 browser 내부의 저장소들이 무엇인지에 대해서 공부해보신다면 더 많은 내용을 공부하시는데 도움이 될거라고 생각해요 🤭

**Comment by johj703** [comment]
네 알겠습니다 다시 제대로 공부해 보겠습니다~
------ Original Message ------
Date: Sunday, Feb 13, 2022 04:45:43 PM
From: "SeungGyu Lee" ***@***.***>
To: "johj703/user_magazine" ***@***.***>
Cc: "Subscribed" ***@***.***>
Subject: [johj703/user_magazine] comment (Issue #1)




로그인 구현에는 현재 문제가 없어보이네요. login한 상태에 대해서 지금 핸들링이 안되어보고 있는걸로 보여집니다. 여기서 이제 모든페이지에서 로그인한 상태를 어떻게 알고 유지할 수 있을까?에 대해서 고민하게 되는데요. 로그인한 상태를 체크하는 로직도 이미 작성해놓은시걸로 보입니다. 하지만 지금 이걸 어떤식으로 유지하고 사용하는지에 대해서 감이 안잡히신다면 현재 직접 작성하신 로그인 관련 로직에 대해서 다시 읽어보시고 Browser의 Cookie storage에 대해서 찾아보시고 이게 어떤건지 무슨 역할을 하는거고 어떻게 사용할 수 있는건지를 공부해보신다면 현재 발생한 문제를 해결하는데 도움이될거라고 생각합니다. 🤓


추가로 cookie뿐 아니라 session storage, local storage 등등 다양한 browser 내부 저장소가 있는데 각각의 차이점이 어떤거고 browser 내부의 저장소들이 무엇인지에 대해서 공부해보신다면 더 많은 내용을 공부하시는데 도움이 될거라고 생각해요 🤭
